version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'


init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 9 x64
  - git reset --hard HEAD
  - npm install
  - node --version

build_script:
  - npm run build

environment:
  GH_TOKEN:
    secure: 0d7484b1ba4b7028d4b5bf3c6174694dd7835f76

test: off
